title: "Marcus Turner-Wood"
description: ""
theme: minima

author: "Marcus Turner-Wood"

minima:
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/marcus-turner-wood/" }

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

header_pages:
  - about.html
  - themes.html

